import student1 from "../../assets/images/student1.png";
import student2 from "../../assets/images/student2.png";

export const courseList = [
  {
    thumbnail: student1,
    title: "The Complete 2024 GATE Course",
    description: "Engineering Mathematics",
    author: "Kundan Kumar",
    rating: "4",
    aggregateRating: "16225",
    duration: "40 Hours",
    bestSeller: false,
    price: "499",
    lectures: "373 Lectures",
    isPaid: true,
  },
  {
    thumbnail: student2,
    title: "The Complete IIT JEE COURSE",
    description: "JEE Mains and Advanced, physics",
    author: " Gautam K",
    rating: "4.4",
    aggregateRating: "199736",
    duration: "60 Hours",
    bestSeller: false,
    price: "699",
    lectures: "289 Lectures",
    isPaid: true,
  },
  {
    thumbnail: student1,
    title: "The Complete 2024 DSAT Course",
    description: "Quantitative Reasoning",
    author: "Ashish Kumar",
    rating: "4.1",
    aggregateRating: "2325",
    duration: "48 Hours",
    bestSeller: false,
    price: "599",
    lectures: "73 Lectures",
    isPaid: true,
  },
  {
    thumbnail: student2,
    title: "Mastering Web Development",
    description: " Learn the essentials of JavaScript, HTML, CSS, and React",
    author: "Anand Kumar",
    rating: "4.8",
    aggregateRating: "99736",
    duration: "54 Hours",
    bestSeller: false,
    price: "1099",
    lectures: "18 Lectures",
    isPaid: false,
  },
  {
    thumbnail: student1,
    title: "The Complete 2024 GRE Course",
    description: "Verbal Reasoning",
    author: "Roshan Kumar",
    rating: "4.7",
    aggregateRating: "13325",
    duration: "48 Hours",
    bestSeller: true,
    price: "999",
    lectures: "193 Lectures",
    isPaid: true,
  },
  {
    thumbnail: student2,
    title: "The Complete 2024 GMAT Course",
    description: "Quantitative Reasoning",
    author: "Sonal Chauhan",
    rating: "4.5",
    aggregateRating: "8925",
    duration: "70 Hours",
    bestSeller: true,
    price: "1999",
    lectures: "90 Lectures",
    isPaid: false,
  },
];

export const courseListByName = [
  "GATE",
  "Web Development",
  "GRE",
  "Mathematics",
];

export const faqList = [
  {
    id: 1,
    ques: "What is this Course",
    ans: "Power Batch is an unique Product that offers Live Interactive Sessions with Best faculties of PW where you can experience instant resolution to your doubts by your class teacher.",
  }, {
    id: 2,
    ques: "What is this Course",
    ans: "Power Batch is an unique Product that offers Live Interactive Sessions with Best faculties of PW where you can experience instant resolution to your doubts by your class teacher.",
  },
  {
    id: 3,
    ques: "What is this Course",
    ans: "Power Batch is an unique Product that offers Live Interactive Sessions with Best faculties of PW where you can experience instant resolution to your doubts by your class teacher.",
  },
  {
    id: 4,
    ques: "What is this Course",
    ans: "Power Batch is an unique Product that offers Live Interactive Sessions with Best faculties of PW where you can experience instant resolution to your doubts by your class teacher.",
  },
];
